package paxi

import (
	"encoding/json"
	"flag"
	"os"

	"github.com/ailidani/paxi/log"
)

var configFile = flag.String("config", "config.json", "Configuration file for paxi replica. Defaults to config.json.")

// Config contains every system configuration
//config结构体：
type Config struct {
	Addrs     map[ID]string `json:"address"`      // address for node communication 结点通信地址
	HTTPAddrs map[ID]string `json:"http_address"` // address for client server communication 客户机-服务器通信地址

	Policy    string  `json:"policy"`    // leader change policy {consecutive, majority} 领导人变动政策{连续，多数}
	Threshold float64 `json:"threshold"` // threshold for policy in WPaxos {n consecutive or time interval in ms}. WPaxos中策略的阈值{n连续或时间间隔（ms}）

	Thrifty        bool    `json:"thrifty"`          // only send messages to a quorum.Thrifty只发送消息到一个quorum
	SmallQuorum    bool	   `json:"smallquorum"`		//only send message to a decided node set
	BufferSize     int     `json:"buffer_size"`      // buffer size for maps. map的buffer大小
	ChanBufferSize int     `json:"chan_buffer_size"` // buffer size for channels.channelbuffer的大小
	MultiVersion   bool    `json:"multiversion"`     // create multi-version database.创建多版本数据库
	Benchmark      Bconfig `json:"benchmark"`        // benchmark configuration

	// for future implementation
	// Batching bool `json:"batching"`
	// Consistency string `json:"consistency"`
	// Codec string `json:"codec"` // codec for message serialization between nodes

	n   int         // total number of nodes
	z   int         // total number of zones
	npz map[int]int // nodes per zone
}

// Config is global configuration singleton generated by init() func below
var config Config

func init() {
	config = MakeDefaultConfig()
}

// GetConfig returns paxi package configuration
func GetConfig() Config {
	return config
}

// Simulation enable go channel transportation to simulate distributed environment
//Simulation 使go-channel传输能够模拟分布式环境
func Simulation() {
	*scheme = "chan"
}

// MakeDefaultConfig returns Config object with few default values
// MakeDefaultConfig()：用于返回config对象，只能被init()和master使用。
func MakeDefaultConfig() Config {
	return Config{
		//Policy：数据读取模式的触发器，可被用于数据迁移协议
		Policy:         "consecutive",
		//WPaxos中策略的阈值{n连续或时间间隔（ms}）
		Threshold:      3,
		BufferSize:     1024,
		ChanBufferSize: 1024,
		MultiVersion:   false,
		Benchmark:      DefaultBConfig(),
	}
}

// IDs returns all node ids
//IDs():返回所有结点ID
func (c Config) IDs() []ID {
	ids := make([]ID, 0)
	for id := range c.Addrs {
		ids = append(ids, id)
	}
	return ids
}

// N returns total number of nodes
//N():返回总共结点数
func (c Config) N() int {
	return c.n
}

// Z returns total number of zones
//Z():返回总zone数
func (c Config) Z() int {
	return c.z
}

// String is implemented to print the config
//String():字符串化config
func (c Config) String() string {
	config, err := json.Marshal(c)
	if err != nil {
		log.Error(err)
		return ""
	}
	return string(config)
}

// Load loads configuration from config file in JSON format
//Load():以JSON格式从配置文件加载配置
func (c *Config) Load() {
	file, err := os.Open(*configFile)
	if err != nil {
		log.Fatal(err)
	}
	decoder := json.NewDecoder(file)
	err = decoder.Decode(c)
	if err != nil {
		log.Fatal(err)
	}

	c.npz = make(map[int]int)
	for id := range c.Addrs {
		c.n++
		c.npz[id.Zone()]++
	}
	c.z = len(c.npz)
}

// Save saves configuration to file in JSON format
//save():以json格式将配置存储在新建的文件中
func (c Config) Save() error {
	file, err := os.Create(*configFile)
	if err != nil {
		return err
	}
	encoder := json.NewEncoder(file)
	return encoder.Encode(c)
}
